### ISSUE TITLE
License and copyright statements are missing

### ISSUE THREAD

**Issue by lextm** [vichal/SharpSnmpLib.MibParser#1]
The code you use is derived from #SNMP Library (version < 7.5). Thus, you should clearly state its open source license as Lesser GPL. Otherwise, you explicitly violate that license by releasing the code.

https://docs.sharpsnmp.com/en/latest/getting-started/license-notice.html

Besides, I still own the copyright of the code, so please add a copyright statement, such as "Copyright (C) 2008 Lex Li". You can of course claim copyright of your modification, but due to LGPL your changes should also be released under LGPL.

Please consider copyright and open source licensing seriously, as they are the keys to govern open source projects.

For the NuGet package, you should also explicit state its open source license as LGPL, and mark me as author (you can also list yourself as co-author if you like). Currently you mark "the authors" as you, which is totally not acceptable.

**Comment by vichal** [comment]
Sorry Lextm, I am a newbie for github. I will change all issues as you said.

**Comment by vichal** [comment]
Lex, I have added the license and upgrade the Nuget package metadata as you mentioned.

**Comment by lextm** [comment]
Looks good.
